### ISSUE TITLE
Can't import.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [tueda/cli-confirm#1]
```log
>>> import cli-confirm
  File "<stdin>", line 1
    import cli-confirm
              ^
SyntaxError: invalid syntax
>>> import "cli-confirm"
  File "<stdin>", line 1
    import "cli-confirm"
           ^^^^^^^^^^^^^
SyntaxError: invalid syntax
>>>
```

**Comment by tueda** [comment]
The module installed by the package is `confirm`. Please use `import confirm`.

**Comment by roke-julian-lockhart** [comment]
@tueda, probably worth adding to the https://github.com/tueda/cli-confirm#readme.

**Comment by tueda** [comment]
You are right. Maybe it should be written that those who want to use this from Python codes should use [`click`](https://github.com/pallets/click) instead.
